/**
 * XmlForm.IO API
 * XmlForm.IO API for working with web forms backed by XML data
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@xmlform.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The JwtLogin200Response model module.
 * @module model/JwtLogin200Response
 * @version 1.0
 */
class JwtLogin200Response {
    /**
     * Constructs a new <code>JwtLogin200Response</code>.
     * @alias module:model/JwtLogin200Response
     */
    constructor() { 
        
        JwtLogin200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>JwtLogin200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/JwtLogin200Response} obj Optional instance to populate.
     * @return {module:model/JwtLogin200Response} The populated <code>JwtLogin200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JwtLogin200Response();

            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>JwtLogin200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>JwtLogin200Response</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['token'] && !(typeof data['token'] === 'string' || data['token'] instanceof String)) {
            throw new Error("Expected the field `token` to be a primitive type in the JSON string but got " + data['token']);
        }

        return true;
    }


}



/**
 * JWT token for authentication
 * @member {String} token
 */
JwtLogin200Response.prototype['token'] = undefined;






export default JwtLogin200Response;

